# Generated by Django 3.0.8 on 2021-03-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
    ]
